language: julia
coveralls: true

os:
  - osx
  - linux

julia:
  - 1
  - nightly

jobs:
  allow_failures:
    - julia: nightly
    
  include:
    - stage: "Test"
      script:
        - julia --project --check-bounds=yes -e 'using Pkg; Pkg.build(; verbose = true); Pkg.test("SimSpin"; coverage=true)'

    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate();'
        - julia --project=docs/ docs/make.jl

      after_success:
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
